### ISSUE TITLE
Facebook too, please! :)

### ISSUE THREAD

**Issue by a-raccoon** [xwipeoutx/undirect#11]
Elegantly simple script. I would love it it also undirected links clicked from facebook too!

Both platforms make it similarly impossible to right-click copy link addresses to external sites, using the same redirect method.

**Comment by webmastir** [comment]
I don't think this is an active project any longer.

**Comment by a-raccoon** [comment]
That would be a shame.  It still works.  Doesn't have any malware or advertising like its competition does.  Has a good marketable name.  Should be expanded and promoted along side Privacy Badger for reducing user tracking.

**Comment by xwipeoutx** [comment]
Well, it's not active because it was complete and, dare I say, bug free! 

The Facebook support sounds like a good idea, I'll check it out, it looks simple enough to do at a glance

**Comment by xwipeoutx** [comment]
Doneski, the Googles says it might take up to an hour to be published.  I'll close it out when I've tested the published version.

**Comment by a-raccoon** [comment]
Daaang that was fast! You're a good man, Charlie Brown.

**Comment by bmelman** [comment]
For a moment I thought this plugin was hacked or gone bad until I checked here (what plugin suddenly needs access to specifically my facebook?!), great work! 👍

**Comment by a-raccoon** [comment]
> what plugin suddenly needs access to specifically my facebook?
How does that work bmelman? I received no permissions query for this addon to strip out facebook's click-tracking redirects. Is that a set of development features or a "plugins firewall" of sorts?

Maybe it'd be a good idea if the settings default to off, allowing the user to opt-in each checkbox for each site it's going to augment links on. *a-raccoon caused such a mess of things!*

**Comment by bmelman** [comment]
My chrome showed a popup when I opened a new (Incognito) Window, telling me undirect was disabled because it needed extra permissions to access facebook.com site info (I don't remember the exact phrase), offering me to allow or delete the extension.

**Comment by xwipeoutx** [comment]
Unfortunately, permissions in Chrome extensions don't work that way - you specify the sites to allow in the manifest, not in the code, so it can't be dynamic or user-selectable.  The first release of the plugin actually said "all data on all sites" until I restricted it to Chrome.

My only options that I can see are
1) Rename the extension to "Undirect for Facebook and Google" so it's clear
2) Make 2 extensions - one for facebook, one for google
3) Leave it as is

I think I'll stick with #3 - perhaps I'm selfish, but this plugin is mainly for myself, and I don't mind it accessing my facebook ^_^

**Comment by bmelman** [comment]
Somehow it was linked to this github repository, so it's fine anyway, anyone who notices it should be wise enough to find out how and what themselves.
(I do start wondering how to check that the installed extension actually is based on this source anyway... lol)

**Comment by a-raccoon** [comment]
It looks like this needs to be updated again.  Facebook likes to tack on ?fbclid=PDpsYoABR-dTfrnqEonoNetWrhfTbPsbEcOuxmOjxtPvuWisnIITMpydodLTP (example) to the end of external links.

**Comment by a-raccoon** [comment]
> (I do start wondering how to check that the installed extension actually is based on this source anyway... lol)

@bmelman The code is in javascript, and js is not compiled.  Open Chrome's Extensions page and View Details for this extension in question.  Note the extension's ID number (eg `dohbiijnjeiejifbgfdhfknogknkglio`).  Locate the folder on your harddrive by the same name.  You will find the .js files in there to compare against the source code on github.
