### ISSUE TITLE
Work with sponsored links on Google

### ISSUE THREAD

**Issue by MachFour** [xwipeoutx/undirect#12]
Hi there,

I just installed this add on from the Chrome store, because I had been having the exact problem of trying to copy links from a Google search but then having a garbled Google URL being put into my clipboard. 

However, this extension doesn't prevent this behaviour for links that come up in the 'sponsored' bit of a Google search. (Despite the status bar in Chrome displaying the correct link location when I hover over it.).
Is there any chance that sponsored links could be supported?

**Comment by xwipeoutx** [comment]
Thanks for the feedback - I debated about this internally for a bit, and decided that I don't want to invoke the wrath of Google by eliminating their search income stream
