### ISSUE TITLE
No longer useful for Google links

### ISSUE THREAD

**Issue by quinncomendant** [xwipeoutx/undirect#13]
Undirect does nothing now. Google no longer uses an intermediary redirect for search result links. Instead, they submit an XHR request to their tracking service when a link is clicked (taken from the `ping="…"` attribute):

    <a href="https://en.wikipedia.org/wiki/Peace" ping="/url?sa=t&amp;source=web&amp;rct=j&amp;url=https://en.wikipedia.org/wiki/Peace&amp;ved=2ahUKEwiVvOGdtL7eAhWBNn0KHYmDBngQFjABegQICxAB">…</a>

**Comment by xwipeoutx** [comment]
Thanks for the report @quinncomendant , I'll have a look into this - I've noticed the XHR doesn't _always_ happen, which is a bit weird.

My main motivation of this library was removing the interstitial page and fixing up the "copy link to clipboard" functionality.  These 2 things are no longer factors - do you get any value out of the extension anymore?

I'm trying to justify continued maintenance of the extension given the value proposition has dropped significantly.

Let me know your thoughts.

**Comment by quinncomendant** [comment]
Both of your main issues (the interstitial page and fixing up the "copy link to clipboard" functionality) no longer exist.

If that is all the extension does, it no longer has any value. 

The extension may have a large user base, many of whom may not realize it can be uninstalled. If you decide to stop maintaining the extension, perhaps you could push an update that turns the extension into a "stub" with a note displayed to the user that it may be uninstalled. Otherwise, you could also push some other useful features, such as disabling Google's new style of hyperlink tracking for improved privacy. 

I use [uMatrix](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf?hl=en), which can disable hyperlink auditing, so it's all I need, for now.
<img width="513" alt="screen shot 2018-11-23 at 14 22 28" src="https://user-images.githubusercontent.com/6884276/48959598-12ee3280-ef2c-11e8-8f81-e56e9db182c8.png">

**Comment by xwipeoutx** [comment]
Finally have had time to look at this - I note that Facebook support is still fine - so there may be some value if you're in the habit of clicking on Facebook ads.

I've pushed a new version out with just Facebook search results - but I won't be using this extension anymore, and will recommend anyone who asks to just uninstall it.

**Comment by devnoname120** [comment]
Google still has redirects for me on Android using Google Chrome.

![Screenshot_20231015-091607_Chrome](https://github.com/xwipeoutx/undirect/assets/2824100/bc93a9cc-a4ac-4f09-b659-600eefb989c5)

Info:
- Android 13
- Google Chrome version 117.0.5938.153
