### ISSUE TITLE
Add firefox version

### ISSUE THREAD

**Issue by xwipeoutx** [xwipeoutx/undirect#4]
Compile to a firefox add-on, too, if simple enough.

**Comment by meteormatt** [comment]
我现在用的是这个.
https://addons.mozilla.org/zh-CN/firefox/addon/google-search-link-fix/
我看了下这个项目的代码, 感觉是基于`userscript`的. 不是不能移植, 只是嫌麻烦不想移植罢了.

**Comment by xwipeoutx** [comment]
Not gonna happen
