### ISSUE TITLE
Not working for the past few weeks

### ISSUE THREAD

**Issue by martinpaljak** [xwipeoutx/undirect#6]
It seems that either Chrome or Google has changed something and the extension does not work any more.

**Comment by xwipeoutx** [comment]
Got any more info on this? Just did a search, clicked the link while capturing network traffic, and it never did the redirect thing.  Tried with the extension disabled, and it went back to previous redirect behaviour.

**Comment by martinpaljak** [comment]
I don't need a capture to confirm this, because before it made it *obvious* that it was working, but now the status bar shows the /url links and also clicks do resolve first to Google.

Looking at the source, I see it omits document.rwt, which I don't see at all, when inspecting a results page with Chrome console. 

 I have no idea how to debug this further but I'm willing to debug it if advised. Did disable all other plugins (ghostery, ublock, https everywhere being the only ones that might maybe interfere) and still the same.

Any tips?

**Comment by martinpaljak** [comment]
I'm running Chrome 44.0.2403.157 (64-bit)

**Comment by xwipeoutx** [comment]
It could be google doing some AB testing, which would make this difficult to reproduce and diagnose. Mind providing the following info:

* Example of a search term, and the exact link being clicked
* Exact URL of initial search page (specifically, if you entered via a country-specific portal)
* URL of search results page
* Are you logged in? What country are you browsing from? Does it happen when not logged in? What about the incognito tab?
* Before interacting with the page at all, and with Undirect disabled, the results of the following commands in the dev tools

```
    document.querySelector('#rso a').outerHTML
```
This selector should be match the link in the first result.  If it doesn't on yours, adjust it accordingly.
    
```
    rwt.toString()
```
(Note this will be `window.rwt`, not `document.rwt`)

Could you also mousedown on one of the links, then dragging away from the link (so the click doesn't trigger), and post the results of the same statements? It's in the mousedown event that the link is rewritten - at least for my results.  You're clearly getting something different.
